import Head from "next/head"
import { useEffect, useState } from "react"

const { URL_PROTOCOL, URL_BASE } = process.env;

export default function Home() {
  const [message, setMessage] = useState({ message: '' });

  const fetchInitialMessage = async () => {
    const data = await fetch(URL_PROTOCOL + URL_BASE);
    setMessage(await data.json());
  };

  useEffect(() => {
    fetchInitialMessage();
  }, []);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        { message.message }
      </main>
    </>
  )
}
